### ISSUE TITLE
Can't input int and float values

### ISSUE THREAD

**Issue by TheRadMatt** [Stoeoeoe/godot_data_editor#6]
Weirdly, in the demo everything works fine but in a new project when I try to put an int or float value (f.e. _damage points_) it doesn't work. The moment I try to save it resets itself back to default value. Tried to use stuff like _(int, 0, 9999)_ or _(float, 0, 999)_ and it doesn't work either. 
Too bad, cause the addon is absolutely amazing and I really want to use it :/

**Comment by Stoeoeoe** [comment]
Hi! Thanks a lot for the report!

I think issue is the same as this one here:
https://github.com/Stoeoeoe/godot_data_editor/issues/3

I tried to find the root of the issue but failed so far, because for me it always worked fine. What might be possible is that the code base of the demo and the code in "addon" are somehow different in some versions. The reason for this may be that I always had to copy all changes from the demo to the addon folder. 

Are you using the newest version, I updated it around a week ago. If yes, could you send me the project/a minimal setup?

**Comment by TheRadMatt** [comment]
Here's a project with your data editor and a int variable example:
[Data_Test.zip](https://github.com/Stoeoeoe/godot_data_editor/files/1346319/Data_Test.zip)

I tried copying both the addons folder from main directory and the folder from demo dir and they both work have this issue.

**Comment by Stoeoeoe** [comment]
Hi, thanks for the file and sorry for the late reply, I will try to look into it on the weekend.

**Comment by Stoeoeoe** [comment]
Sorry for not fixing it earlier, I was rather busy lately...
I think I corrected the issue, could you please check if the issue still occurs with the newest version? It was just a simple check that was missing. Could you check if it works now?

**Comment by TheRadMatt** [comment]
Integers work fine now but there's a weird problem with saving float values. The only way to change a float is to write it, then **deselect** the input area and then save. If the input area for the float value is selected, clicking either _save_ or _save all_ will reset the value to the float that was written last time.

**Comment by Stoeoeoe** [comment]
Whoops, that was probably due to the fact that the changes were no longer picked up properly. Sorry about that. I cleaned up the code a bit and it seems to work fine for me now. I tested integers and floats, with and without constraints as well as integer enums, just to make sure.
